services:
  order-service:
    image: shrenikmehar/order-service:latest
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8080:8080"

  payment-service:
    image: shrenikmehar/payment-service:latest
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8081:8081"
